---
- name: Test using assert 
  hosts: all
  become: true 
  gather_facts: false
  tasks:
    - name: Store date output for timezone check
      command: date
      register: check_tz
      
    - name: check tz
      assert:
        that: "'UTC' in check_tz.stdout"
        
        
...